<?php

/**
 * Model_Base_RolePermission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $role_id
 * @property integer $permission_id
 * @property Model_Permission $Permission
 * @property Model_Role $Role
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_RolePermission extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('role_permission');
        $this->hasColumn('role_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('permission_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_Permission as Permission', array(
             'local' => 'permission_id',
             'foreign' => 'id'));

        $this->hasOne('Model_Role as Role', array(
             'local' => 'role_id',
             'foreign' => 'id'));
    }
}