<?php

/**
 * Model_Base_Status
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $parent_id
 * @property Doctrine_Collection $Status
 * @property Doctrine_Collection $Hotel
 * @property Doctrine_Collection $User
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_Status extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('status');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('parent_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Model_Status as Status', array(
             'local' => 'id',
             'foreign' => 'parent_id'));

        $this->hasMany('Model_Hotel as Hotel', array(
             'local' => 'id',
             'foreign' => 'status_id'));

        $this->hasMany('Model_User as User', array(
             'local' => 'id',
             'foreign' => 'status_id'));
    }
}