<form action="/login/getin" method="POST">
    <table>
        <tr>        
            <td><input type="text" name="username" id="username" placeholder="Utente"></td>
        </tr>
        <tr>
            <td><input type="password" name="password" id="password" placeholder="Contrasegna"></td>
        </tr>
        <tr>
            <td><input type="submit" value="Accedi"></td>
        </tr>
    </table>
</form>