<!DOCTYPE html>
<html lang="it">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>easiSoft.net | Hotel</title>
        <!-- Bootstrap Core CSS -->
        <link href="/css/bootstrap.min.css" rel="stylesheet">
        <!-- Custom CSS -->
        <link href="/css/sb-admin.css" rel="stylesheet">
        <!-- Custom Fonts -->
        <link href="/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <div id="wrapper">
            <!-- Navigation -->
            <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">easiSoft.net | Hotel</a>
                </div>
                <!-- Top Menu Items -->
                <ul class="nav navbar-right top-nav">                
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> <?php echo $this->logged_username; ?> <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="/login/logout"><i class="fa fa-fw fa-power-off"></i> Esci</a>
                            </li>
                        </ul>
                    </li>
                </ul>
                <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
                <div class="collapse navbar-collapse navbar-ex1-collapse">
                    <ul class="nav navbar-nav side-nav">
                        <li>
                            <a href="javascript:;" data-toggle="collapse" data-target="#hotelclp">Hotel <i class="fa fa-fw fa-caret-down"></i></a>
                            <ul id="hotelclp" class="collapse">
                                <li>
                                    <a href="/hotel">Lista</a>
                                </li>
                                <li><?php if ($this->permissions->hasPermission('add_hotel')) :?>
                                    <a href="/hotel/add">Aggiungi</a>
                                </li><?php endif; ?>
                            </ul>
                        </li><?php if(($this->permissions->hasPermission('list_users')) || ($this->permissions->hasPermission('add_user'))) : ?>
                         <li>
                            <a href="javascript:;" data-toggle="collapse" data-target="#utenticlp">Utenti <i class="fa fa-fw fa-caret-down"></i></a>
                            <ul id="utenticlp" class="collapse"><?php if ($this->permissions->hasPermission('list_users')) :?>
                                <li>
                                    <a href="/user">Lista</a>
                                </li><?php endif; ?><?php if ($this->permissions->hasPermission('add_user')) :?>
                                <li>
                                    <a href="/user/add">Aggiungi</a>
                                </li><?php endif; ?>
                            </ul>
                        </li> <?php endif; ?>                       
                    </ul>
                </div>
                <!-- /.navbar-collapse -->
            </nav>
            <div id="page-wrapper">
                <div class="container-fluid">
                    <div class="row">
                        <?php echo $this->layout()->content; ?>
                    </div>                    
                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- /#page-wrapper -->
        </div>
        <!-- /#wrapper -->
        <!-- jQuery -->
        <script src="/js/jquery.js"></script>
        <!-- Bootstrap Core JavaScript -->
        <script src="/js/bootstrap.min.js"></script>
    </body>
</html>