<!DOCTYPE html>
<html lang="it">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Easisoft.net | Hotel</title>
        <!-- Bootstrap Core CSS -->
        <link href="/css/bootstrap.min.css" rel="stylesheet">
        <!-- Custom CSS -->
        <link href="/css/sb-admin.css" rel="stylesheet">
        <!-- Custom Fonts -->
        <link href="/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <div id="page-wrapper">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4"></div>
                    <div class="col-lg-4">                
                        <form action="/login/getin" method="POST">
                            <div class="form-group">  
                                <input  class="form-control" type="text" name="username" id="username" placeholder="Utente">                
                            </div>
                            <div class="form-group">   
                                <input class="form-control" type="password" name="password" id="password" placeholder="Contrasegna">                
                            </div>
                            <button type="submit" class="btn btn-success">Accedi</button>
                        </form>
                    </div>
                    <div class="col-lg-4"></div>
                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- /#page-wrapper -->
            <!-- jQuery -->
            <script src="/js/jquery.js"></script>
            <!-- Bootstrap Core JavaScript -->
            <script src="/js/bootstrap.min.js"></script>
    </body>
</html>