<?php

/**
 * Model_HotelPriceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_HotelPriceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_HotelPriceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_HotelPrice');
    }
}