<?php

/**
 * Model_HotelUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_HotelUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_HotelUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_HotelUser');
    }
}