<?php

/**
 * Model_HotelTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_HotelTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_HotelTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Hotel');
    }
}