<?php

/**
 * Model_PermissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_PermissionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_PermissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Permission');
    }
}