<?php

/**
 * Model_RoleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_RoleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_RoleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Role');
    }
}