<?php

/**
 * Model_RolesNorootTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_RolesNorootTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_RolesNorootTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_RolesNoroot');
    }
}