<?php

/**
 * Model_RolePermissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_RolePermissionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_RolePermissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_RolePermission');
    }
}