<?php

/**
 * Model_StatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_StatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_StatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Status');
    }
}