<div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">[ID <?php echo $this->hotelData->id; ?>] <?php echo $this->hotelData->name; ?> <small>Aggiungere utente</small></h2>
    </div>
    <div class="col-lg-6">      
        <form action="/hotel/assignnewuser" method="POST">        
            <input type="hidden" name="hotel_id" id="hotel_id" value="<?php echo $this->hotelData->id; ?>">
            <div class="form-group">
                <label>Utente</label>
                <select class="form-control" name="user_id">
                    <option>- Scegli un utente -</option><?php foreach ($this->userListData as $userItem) :?>
                    <option value="<?php echo $userItem->id; ?>"><?php echo $userItem->username; ?></option><?php endforeach; ?>
                </select>                
            </div>
            <button type="submit" class="btn btn-success">Aggiungi</button>
            <a href="/hotel/overview/id/<?php echo $this->hotelData->id; ?>" class="btn btn-warning">Indietro</a>
        </form>
    </div>
</div>